all:
  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    logout:                       true
    site:                         My Site
    include_path:                 true
    include_jquery:               true
    include_jquery_no_conflict:   false
    jquery_filename:              jquery-1.3.2.min.js
    login_route:                  @sf_guard_signin
    logout_route:                 @sf_guard_signout
    